// src/exporters/code-emitters/angular-emitter.ts
/**
 * Angular Emitter — Generates an Angular icon component.
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializeSvg } from '../../engine/svg-parser.js';

export interface AngularEmitterOptions {
  componentName: string;
  selector?: string;
}

export function emitAngular(doc: SvgDocument, options: AngularEmitterOptions): string {
  const { componentName } = options;
  const selector = options.selector ?? `app-icon-${toKebab(componentName)}`;
  const svgString = serializeSvg(doc);

  return `import { Component, Input } from '@angular/core';

@Component({
  selector: '${selector}',
  standalone: true,
  template: \`
    ${svgString.replace(/"/g, "'")}
  \`,
  styles: [\`
    :host { display: inline-flex; }
    svg { width: 100%; height: 100%; }
  \`]
})
export class ${componentName}Component {
  @Input() size = ${doc.viewBox.width};
  @Input() color = 'currentColor';
}
// Generated by IconCraft AI
`;
}

function toKebab(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

// src/exporters/code-emitters/react-emitter.ts
/**
 * React Emitter — Generates a React/JSX icon component.
 * PRD §4B: "Web: Angular/React/Vue."
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializeSvg } from '../../engine/svg-parser.js';

export interface ReactEmitterOptions {
  componentName: string;
  typescript?: boolean;
}

export function emitReact(doc: SvgDocument, options: ReactEmitterOptions): string {
  const { componentName, typescript = true } = options;
  const svgContent = getInnerSvg(doc);
  const vb = `${doc.viewBox.x} ${doc.viewBox.y} ${doc.viewBox.width} ${doc.viewBox.height}`;
  const w = doc.width ?? doc.viewBox.width;
  const h = doc.height ?? doc.viewBox.height;

  const propsType = typescript ? ': React.SVGProps<SVGSVGElement>' : '';
  const ext = typescript ? 'tsx' : 'jsx';

  return `import React from 'react';

export const ${componentName} = (props${propsType}) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="${vb}"
    width={${w}}
    height={${h}}
    fill="none"
    stroke="currentColor"
    {...props}
  >
    ${svgContent}
  </svg>
);

${componentName}.displayName = '${componentName}';
// Generated by IconCraft AI — ${ext}
`;
}

function getInnerSvg(doc: SvgDocument): string {
  const full = serializeSvg(doc);
  const inner = full.replace(/<svg[^>]*>/, '').replace(/<\/svg>/, '').trim();
  return inner;
}
